# Generated by Django 6.0 on 2026-02-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='rate',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='daily_book.itemcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='gsm',
            field=models.PositiveIntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
