# Generated by Django 6.0 on 2026-02-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_book', '0002_remove_purchaseitem_rate_purchaseitem_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdailyentry',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='shopdailyentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='shopdailyentry',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='shopdailyentry',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='shopdailyentry',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='shopdailyentry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shopdailyentry',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='shopdailyentry',
            name='side',
        ),
        migrations.AddField(
            model_name='shopdailyentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shopdailyentry',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('UPI', 'UPI')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ShopDailyEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=150, null=True)),
                ('side', models.CharField(choices=[('single', 'Single Side'), ('double', 'Double Side')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daily_book.shopdailyentry')),
                ('finishing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daily_book.finishing')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_book.stockitem')),
            ],
        ),
    ]
