# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_book', '0004_alter_customer_id_alter_customerpayment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveIntegerField()),
                ('max_count', models.PositiveIntegerField(blank=True, null=True)),
                ('normal_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('press_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_slabs', to='daily_book.finishing')),
            ],
            options={
                'ordering': ('min_count', 'max_count', 'id'),
            },
        ),
    ]
