# Generated by Django 6.0 on 2026-04-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_book', '0005_finishingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveIntegerField()),
                ('max_count', models.PositiveIntegerField(blank=True, null=True)),
                ('normal_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('press_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_slabs', to='daily_book.stockitem')),
            ],
            options={
                'ordering': ('min_count', 'max_count', 'id'),
            },
        ),
    ]
