# Generated by Django 6.0 on 2026-04-22 08:54

from django.db import migrations, models


def backfill_daily_entry_item_rates(apps, schema_editor):
    ShopDailyEntryItem = apps.get_model('daily_book', 'ShopDailyEntryItem')
    for item in ShopDailyEntryItem.objects.all().iterator():
        item.paper_rate = item.rate
        item.finishing_rate = 0
        item.save(update_fields=['paper_rate', 'finishing_rate'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('daily_book', '0006_stockitemrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingrate',
            name='side',
            field=models.CharField(choices=[('single', 'Single Side'), ('double', 'Double Side')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='shopdailyentryitem',
            name='finishing_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shopdailyentryitem',
            name='paper_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockitemrate',
            name='side',
            field=models.CharField(choices=[('single', 'Single Side'), ('double', 'Double Side')], default='single', max_length=10),
        ),
        migrations.RunPython(backfill_daily_entry_item_rates, noop_reverse),
    ]
